from edulink.apps.trust.rules import (
    STUDENT_TRUST_EVENT_POINTS,
    STUDENT_TRUST_LEVELS,
    STUDENT_TRUST_THRESHOLDS,
)

# Backward-compatible aliases. Canonical definitions live in trust.rules.
TRUST_TIER_LEVELS = STUDENT_TRUST_LEVELS
TRUST_EVENT_POINTS = STUDENT_TRUST_EVENT_POINTS
TRUST_TIER_THRESHOLDS = STUDENT_TRUST_THRESHOLDS
