"""Shared API utilities and inter-service communication patterns."""

from .inter_service_communication import (
    ServiceType,
    CommunicationMethod,
    ServiceEndpoint,
    APIRequest,
    APIResponse,
    ServiceRegistry,
    InterServiceClient,
    AuthServiceClient,
    UserServiceClient,
    InstitutionServiceClient,
    NotificationServiceClient,
    ServiceClientFactory,
    CircuitBreaker,
    CommunicationPatterns,
    service_client_factory,
    get_auth_client,
    get_user_client,
    get_institution_client,
    get_notification_client,
)

__all__ = [
    'ServiceType',
    'CommunicationMethod',
    'ServiceEndpoint',
    'APIRequest',
    'APIResponse',
    'ServiceRegistry',
    'InterServiceClient',
    'AuthServiceClient',
    'UserServiceClient',
    'InstitutionServiceClient',
    'NotificationServiceClient',
    'ServiceClientFactory',
    'CircuitBreaker',
    'CommunicationPatterns',
    'service_client_factory',
    'get_auth_client',
    'get_user_client',
    'get_institution_client',
    'get_notification_client',
]