# Generated by Django 4.2.7 on 2025-09-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        help_text="Previous status for audit trail",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the status was last changed",
                        null=True,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("interview_date", models.DateTimeField(blank=True, null=True)),
                ("interview_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField()),
                ("rating", models.PositiveSmallIntegerField()),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.application",
                    ),
                ),
            ],
        ),
    ]
