# Generated by Django 5.2 on 2025-07-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('internship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add nullable foreign key fields WITHOUT constraints
        migrations.AddField(
            model_name="application",
            name="internship_id",
            field=models.BigIntegerField(
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewed_by_id",
            field=models.UUIDField(
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status_changed_by_id",
            field=models.UUIDField(
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="student_id",
            field=models.UUIDField(
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="supervisorfeedback",
            name="application_id",
            field=models.BigIntegerField(
                null=True,
                blank=True,
            ),
        ),
    ]
