# Generated by Django 5.2 on 2025-07-30 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20250730_1035'),
        ('internship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 2: Add foreign key constraints to existing columns
        migrations.RunSQL(
            "ALTER TABLE application_application ADD CONSTRAINT application_applicat_internship_id_2ccbb053_fk_internshi FOREIGN KEY (internship_id) REFERENCES internship_internship(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE application_application DROP CONSTRAINT application_applicat_internship_id_2ccbb053_fk_internshi;"
        ),
        migrations.RunSQL(
            "ALTER TABLE application_application ADD CONSTRAINT application_applicat_reviewed_by_id_8f2a1b4c_fk_auth_user FOREIGN KEY (reviewed_by_id) REFERENCES authentication_user(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE application_application DROP CONSTRAINT application_applicat_reviewed_by_id_8f2a1b4c_fk_auth_user;"
        ),
        migrations.RunSQL(
            "ALTER TABLE application_application ADD CONSTRAINT application_applicat_status_changed_by_id_9e3c2d5f_fk_auth_user FOREIGN KEY (status_changed_by_id) REFERENCES authentication_user(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE application_application DROP CONSTRAINT application_applicat_status_changed_by_id_9e3c2d5f_fk_auth_user;"
        ),
        migrations.RunSQL(
            "ALTER TABLE application_application ADD CONSTRAINT application_applicat_student_id_7a4b8c9d_fk_auth_user FOREIGN KEY (student_id) REFERENCES authentication_user(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE application_application DROP CONSTRAINT application_applicat_student_id_7a4b8c9d_fk_auth_user;"
        ),
        migrations.RunSQL(
            "ALTER TABLE application_supervisorfeedback ADD CONSTRAINT application_supervisorf_application_id_1f5e9a2b_fk_applicati FOREIGN KEY (application_id) REFERENCES application_application(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE application_supervisorfeedback DROP CONSTRAINT application_supervisorf_application_id_1f5e9a2b_fk_applicati;"
        ),
        # Add indexes
        migrations.RunSQL(
            "CREATE INDEX application_status_66d7e3_idx ON application_application (status, application_date);",
            reverse_sql="DROP INDEX application_status_66d7e3_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX application_student_db6318_idx ON application_application (student_id, status);",
            reverse_sql="DROP INDEX application_student_db6318_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX application_interns_37a36a_idx ON application_application (internship_id, status);",
            reverse_sql="DROP INDEX application_interns_37a36a_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX application_status__3de0fb_idx ON application_application (status_changed_at);",
            reverse_sql="DROP INDEX application_status__3de0fb_idx;"
        ),
        # Add unique constraint
        migrations.RunSQL(
            "ALTER TABLE application_application ADD CONSTRAINT application_application_student_id_internship_id_unique UNIQUE (student_id, internship_id);",
            reverse_sql="ALTER TABLE application_application DROP CONSTRAINT application_application_student_id_internship_id_unique;"
        ),
    ]
