# Generated by Django 5.2 on 2025-08-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20250730_1050'),
        ('internship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorfeedback',
            name='application_id',
        ),
        migrations.AddField(
            model_name='application',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internship.internship'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='Who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'internship')},
        ),
        migrations.AddField(
            model_name='supervisorfeedback',
            name='application',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'application_date'], name='application_status_66d7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'status'], name='application_student_db6318_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['internship', 'status'], name='application_interns_37a36a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status_changed_at'], name='application_status__3de0fb_idx'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_by_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status_changed_by_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_id',
        ),
    ]
