# Generated by Django 5.2.4 on 2025-07-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='institutionprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email_verified',
        ),
    ]
