# Generated by Django 5.2 on 2025-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, help_text='Academic year for university search method', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Student gender', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='registration_method',
            field=models.CharField(choices=[('university_code', 'University Code'), ('university_search', 'University Search')], default='university_search', help_text='Method used for registration', max_length=20),
        ),
    ]
