# Generated by Django 5.2.4 on 2025-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_employerprofile_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
