# Generated by Django 5.2.3 on 2025-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employerprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
