# Generated by Django 5.2.4 on 2025-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_studentprofile_github_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="profile_completion",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
