# Generated by Django 5.2.4 on 2025-07-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_studentprofile_profile_completion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="profile_completion",
        ),
    ]
