# Generated by Django 5.2.6 on 2026-01-24 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("official_email", models.EmailField(max_length=254)),
                ("domain", models.CharField(max_length=255)),
                ("organization_type", models.CharField(max_length=50)),
                ("contact_person", models.CharField(max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "trust_level",
                    models.IntegerField(
                        choices=[
                            (0, "Unverified"),
                            (1, "Verified Entity"),
                            (2, "Active Host"),
                            (3, "Trusted Partner"),
                        ],
                        default=0,
                    ),
                ),
                ("max_active_students", models.PositiveIntegerField(default=5)),
                ("supervisor_ratio", models.PositiveIntegerField(default=5)),
            ],
            options={
                "db_table": "employers",
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisors",
                        to="employers.employer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supervisors",
                "unique_together": {("employer", "user")},
            },
        ),
    ]
