# Generated by Django 5.2.6 on 2026-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisor",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Employer Admin"), ("SUPERVISOR", "Supervisor")],
                default="SUPERVISOR",
                max_length=20,
            ),
        ),
    ]
