# Generated by Django 5.2.6 on 2026-01-24 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0002_supervisor_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("official_email", models.EmailField(max_length=254)),
                ("domain", models.CharField(max_length=255)),
                ("organization_type", models.CharField(max_length=50)),
                ("contact_person", models.CharField(max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INVALID_DOMAIN", "Invalid Domain"),
                            ("DUPLICATE", "Duplicate Entry"),
                            ("SUSPICIOUS", "Suspicious Activity"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "employer_requests",
                "indexes": [
                    models.Index(
                        fields=["status"], name="employer_re_status_5a915a_idx"
                    ),
                    models.Index(
                        fields=["tracking_code"], name="employer_re_trackin_a9f862_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployerInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="employers.employer",
                    ),
                ),
            ],
            options={
                "db_table": "employer_invites",
                "indexes": [
                    models.Index(
                        fields=["email", "status"], name="employer_in_email_735ed2_idx"
                    ),
                    models.Index(
                        fields=["token_hash"], name="employer_in_token_h_ae4c9b_idx"
                    ),
                ],
            },
        ),
    ]
