# Generated by Django 5.2.6 on 2026-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0003_employerrequest_employerinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerrequest",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
