# Generated by Django 5.2.6 on 2026-01-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0004_employerrequest_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
