# Generated by Django 5.2.6 on 2026-01-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0005_employer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerinvite",
            name="role",
            field=models.CharField(default="ADMIN", max_length=20),
        ),
    ]
