# Generated by Django 5.2.6 on 2026-01-27 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0006_employerinvite_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerStaffProfileRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_changes",
                    models.JSONField(
                        help_text="Dictionary of requested changes (first_name, last_name, email)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_feedback", models.TextField(blank=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile_requests",
                        to="employers.employer",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_requests",
                        to="employers.supervisor",
                    ),
                ),
            ],
            options={
                "db_table": "employer_staff_profile_requests",
                "indexes": [
                    models.Index(
                        fields=["employer", "status"],
                        name="employer_st_employe_247ccd_idx",
                    ),
                    models.Index(
                        fields=["staff", "status"],
                        name="employer_st_staff_i_e33fd5_idx",
                    ),
                ],
            },
        ),
    ]
