# Generated by Django 5.2.6 on 2026-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0007_employerstaffprofilerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employer",
            name="max_active_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employer",
            name="supervisor_ratio",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
