# Generated by Django 5.2.6 on 2026-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0008_employer_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="System derived status for featured employers"
            ),
        ),
    ]
