# Generated by Django 5.2.6 on 2026-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0009_alter_employer_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="employer_logos/"),
        ),
    ]
