# Employer Status
EMPLOYER_STATUS_REQUESTED = "REQUESTED"
EMPLOYER_STATUS_APPROVED = "APPROVED"
EMPLOYER_STATUS_ACTIVE = "ACTIVE"
EMPLOYER_STATUS_REJECTED = "REJECTED"

EMPLOYER_STATUS_CHOICES = [
    (EMPLOYER_STATUS_REQUESTED, "Requested"),
    (EMPLOYER_STATUS_APPROVED, "Approved"),
    (EMPLOYER_STATUS_ACTIVE, "Active"),
    (EMPLOYER_STATUS_REJECTED, "Rejected"),
]

# Employer Trust Levels
EMPLOYER_TRUST_UNVERIFIED = 0
EMPLOYER_TRUST_VERIFIED = 1
EMPLOYER_TRUST_ACTIVE_HOST = 2
EMPLOYER_TRUST_PARTNER = 3

EMPLOYER_TRUST_CHOICES = [
    (EMPLOYER_TRUST_UNVERIFIED, "Unverified"),
    (EMPLOYER_TRUST_VERIFIED, "Verified Entity"),
    (EMPLOYER_TRUST_ACTIVE_HOST, "Active Host"),
    (EMPLOYER_TRUST_PARTNER, "Trusted Partner"),
]
