# Generated by Django 5.2.6 on 2026-01-30 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_id",
                    models.UUIDField(help_text="Reference to InternshipApplication"),
                ),
                ("student_id", models.UUIDField(help_text="Reference to Student")),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("CERTIFICATE", "Certificate of Completion"),
                            ("LOGBOOK_REPORT", "Internship Logbook Report"),
                            ("PERFORMANCE_SUMMARY", "Performance Summary"),
                        ],
                        default="LOGBOOK_REPORT",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The generated PDF file", upload_to="artifacts/%Y/%m/"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contextual data used for generation",
                    ),
                ),
                (
                    "generated_by",
                    models.UUIDField(help_text="User ID who triggered the generation"),
                ),
            ],
            options={
                "db_table": "generated_artifacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application_id"], name="generated_a_applica_0d60ba_idx"
                    ),
                    models.Index(
                        fields=["student_id"], name="generated_a_student_d0556d_idx"
                    ),
                    models.Index(
                        fields=["artifact_type"], name="generated_a_artifac_8858f5_idx"
                    ),
                ],
            },
        ),
    ]
