# Generated by Django 5.2.6 on 2026-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                help_text="Unique verification code (e.g. EDULINK-ABC123)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["tracking_code"], name="generated_a_trackin_3468ab_idx"
            ),
        ),
    ]
