# Generated by Django 5.0.4 on 2026-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_artifact_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When generation completed', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if generation failed', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Generation queued'), ('PROCESSING', 'Currently generating'), ('SUCCESS', 'Generation successful'), ('FAILED', 'Generation failed')], default='PENDING', help_text='Artifact generation state', max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(blank=True, help_text='The generated PDF file', null=True, upload_to='artifacts/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['status'], name='generated_a_status_eec428_idx'),
        ),
    ]
