# Generated by Django 5.2.4 on 2025-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skilltag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
