# Generated by Django 5.1.7 on 2025-07-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
        ('users', '0003_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='is_verified_by_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institutionprofile'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
