# Generated by Django 4.2.7 on 2025-09-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("internship", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internships",
                to="users.employerprofile",
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internships",
                to="users.institutionprofile",
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="partner_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution this internship is specifically for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_internships",
                to="users.institutionprofile",
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="skill_tags",
            field=models.ManyToManyField(
                blank=True, related_name="internships", to="internship.skilltag"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.institutionprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["category", "location_type"],
                name="internship__categor_f7e13a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["deadline", "is_active"], name="internship__deadlin_f2e4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["start_date", "end_date"], name="internship__start_d_83d6f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["employer", "is_active"], name="internship__employe_f7b313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["is_featured", "created_at"],
                name="internship__is_feat_23e272_idx",
            ),
        ),
    ]
