# Generated by Django 5.2.1 on 2025-07-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_skilltag_alter_application_options_and_more'),
        ('users', '0003_employerprofile_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
        migrations.AddField(
            model_name='internship',
            name='flag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='is_verified_by_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='verification_status',
            field=models.CharField(choices=[('auto_verified', 'Auto Verified'), ('pending_review', 'Pending Review'), ('flagged', 'Flagged')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institutionprofile'),
        ),
        migrations.CreateModel(
            name='FlagReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_reports', to='internship.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_reports', to='users.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
