# Generated by Django 5.2.6 on 2025-09-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internship", "0003_externalopportunitysource_externalopportunity"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="created_by_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution that created this internship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_internships",
                to="users.institutionprofile",
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internships",
                to="users.employerprofile",
            ),
        ),
    ]
