# Generated by Django 5.2.6 on 2025-09-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0003_partnership_partnershipactivity_and_more"),
        ("internship", "0004_internship_created_by_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic department for institution-created internships",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internships",
                to="institutions.department",
            ),
        ),
    ]
