# Generated by Django 5.2.6 on 2026-02-07 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_admin", "0002_alter_adminactionlog_action"),
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to="platform_admin.platformstaffprofile",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECHNICAL", "Technical Issue"),
                    ("AFFILIATION", "Affiliation Query"),
                    ("INTERNSHIP", "Internship Assistance"),
                    ("ACCOUNT", "Account Management"),
                    ("OTHER", "General Inquiry"),
                ],
                default="OTHER",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="LOW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="related_entity_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="related_entity_type",
            field=models.CharField(
                blank=True, help_text="e.g., InternshipApplication", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="tracking_code",
            field=models.CharField(
                db_index=True, default=8, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="supportticket",
            table="support_tickets",
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="support/attachments/")),
                ("file_name", models.CharField(max_length=255)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "db_table": "support_ticket_attachments",
            },
        ),
        migrations.CreateModel(
            name="TicketCommunication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Visible only to staff"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "db_table": "support_ticket_communications",
                "ordering": ["created_at"],
            },
        ),
    ]
