# Generated by Django 5.2.6 on 2026-02-07 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0002_supportticket_assigned_to_supportticket_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportticket",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="supportticket",
            name="assigned_to_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["status"], name="support_tic_status_ac1ffd_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["category"], name="support_tic_categor_760901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["priority"], name="support_tic_priorit_3536fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["email"], name="support_tic_email_225c91_idx"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["assigned_to_id"], name="support_tic_assigne_be03da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["user"], name="support_tic_user_id_f7e679_idx"),
        ),
    ]
