# Generated by Django 5.2.6 on 2025-09-15 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("snapshot_date", models.DateTimeField()),
                ("metrics_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.institutionprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["snapshot_type", "snapshot_date"],
                        name="analytics_m_snapsho_e3533d_idx",
                    ),
                    models.Index(
                        fields=["institution", "snapshot_type", "snapshot_date"],
                        name="analytics_m_institu_ece8ac_idx",
                    ),
                ],
                "unique_together": {("snapshot_type", "snapshot_date", "institution")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_completion_rate", "Low Completion Rate"),
                            ("high_response_time", "High Response Time"),
                            ("low_application_rate", "Low Application Rate"),
                            ("system_performance", "System Performance Issue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("threshold_value", models.FloatField()),
                ("current_value", models.FloatField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.institutionprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_type", "is_resolved", "created_at"],
                        name="analytics_p_alert_t_8287c4_idx",
                    ),
                    models.Index(
                        fields=["institution", "is_resolved", "created_at"],
                        name="analytics_p_institu_f14a6a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RealTimeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total_students", "Total Students"),
                            ("active_internships", "Active Internships"),
                            ("completion_rate", "Completion Rate"),
                            ("application_rate", "Application Rate"),
                            ("placement_rate", "Placement Rate"),
                            ("response_time", "Average Response Time"),
                            ("user_activity", "User Activity"),
                            ("system_performance", "System Performance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.institutionprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "timestamp"],
                        name="analytics_r_metric__a95ae8_idx",
                    ),
                    models.Index(
                        fields=["institution", "metric_type", "timestamp"],
                        name="analytics_r_institu_1376f2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=50)),
                ("page_path", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=100)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="analytics_u_user_id_391379_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "timestamp"],
                        name="analytics_u_activit_1f5653_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="analytics_u_session_a23d2f_idx",
                    ),
                ],
            },
        ),
    ]
