# Generated by Django 5.2.6 on 2025-09-15 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("comprehensive", "Comprehensive Report"),
                            ("analytics", "Analytics Report"),
                            ("performance", "Performance Report"),
                            ("engagement", "Engagement Report"),
                            ("internship", "Internship Report"),
                            ("partnership", "Partnership Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for integrity",
                        max_length=64,
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        default=dict, help_text="Actual report data/content"
                    ),
                ),
                (
                    "generation_parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used to generate the report"
                    ),
                ),
                (
                    "summary_stats",
                    models.JSONField(
                        default=dict, help_text="Summary statistics from the report"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report expires", null=True
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Whether report is publicly accessible"
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False, help_text="Whether this is a scheduled report"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="users.institutionprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "status", "created_at"],
                        name="analytics_r_report__e6d3ca_idx",
                    ),
                    models.Index(
                        fields=["institution", "report_type", "created_at"],
                        name="analytics_r_institu_c6fd4b_idx",
                    ),
                    models.Index(
                        fields=["generated_by", "created_at"],
                        name="analytics_r_generat_c4eaba_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="analytics_r_status_3e008b_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="analytics_r_period__4f52c4_idx",
                    ),
                ],
            },
        ),
    ]
