# Generated by Django 5.2.6 on 2025-09-13 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="institutions.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("institution", "code")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["institution", "is_active"],
                name="institution_institu_ed41ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["department", "is_active"],
                name="institution_departm_e9e869_idx",
            ),
        ),
    ]
