# Generated by Django 5.2.6 on 2025-09-13 18:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0002_course_created_at_course_department_and_more"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the partnership program", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the partnership"
                    ),
                ),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship Program"),
                            ("placement", "Job Placement"),
                            ("research", "Research Collaboration"),
                            ("training", "Training Program"),
                            ("mentorship", "Mentorship Program"),
                            ("general", "General Partnership"),
                        ],
                        default="internship",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Partnership start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Partnership end date (optional for ongoing partnerships)",
                        null=True,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically renew partnership when it expires",
                    ),
                ),
                (
                    "renewal_period_months",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Renewal period in months",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of students for this partnership",
                        null=True,
                    ),
                ),
                (
                    "current_students",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of students in the partnership",
                    ),
                ),
                (
                    "institution_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person from institution",
                        max_length=255,
                    ),
                ),
                (
                    "institution_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from institution",
                        max_length=254,
                    ),
                ),
                (
                    "institution_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone from institution",
                        max_length=20,
                    ),
                ),
                (
                    "employer_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person from employer",
                        max_length=255,
                    ),
                ),
                (
                    "employer_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email from employer",
                        max_length=254,
                    ),
                ),
                (
                    "employer_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone from employer",
                        max_length=20,
                    ),
                ),
                (
                    "agreement_document",
                    models.FileField(
                        blank=True,
                        help_text="Partnership agreement document",
                        null=True,
                        upload_to="partnerships/agreements/",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Specific terms and conditions for this partnership",
                    ),
                ),
                (
                    "benefits_offered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of benefits offered (e.g., ['Mentorship', 'Training', 'Certification'])",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of requirements (e.g., ['GPA > 3.0', 'Technical Skills', 'Interview'])",
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Success rate percentage of the partnership",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "satisfaction_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Average satisfaction score (0-5)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "total_placements",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of successful placements"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the partnership was approved",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this partnership",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_partnerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this partnership",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_partnerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="users.employerprofile",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="users.institutionprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnershipActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Partnership Created"),
                            ("approved", "Partnership Approved"),
                            ("suspended", "Partnership Suspended"),
                            ("renewed", "Partnership Renewed"),
                            ("terminated", "Partnership Terminated"),
                            ("student_added", "Student Added"),
                            ("student_removed", "Student Removed"),
                            ("meeting", "Meeting Conducted"),
                            ("communication", "Communication"),
                            ("review", "Partnership Review"),
                            ("other", "Other Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the activity", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the activity"
                    ),
                ),
                (
                    "participants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of participants in the activity",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of attachment file paths",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the activity"
                    ),
                ),
                (
                    "activity_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the activity occurred",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who logged this activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partnership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="institutions.partnership",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date"],
            },
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["status", "partnership_type"],
                name="institution_status_72bc8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["start_date", "end_date"], name="institution_start_d_1629b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["institution", "status"], name="institution_institu_b37d23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["employer", "status"], name="institution_employe_c791a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["priority", "status"], name="institution_priorit_f8f62e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partnership",
            unique_together={("institution", "employer", "name")},
        ),
        migrations.AddIndex(
            model_name="partnershipactivity",
            index=models.Index(
                fields=["partnership", "activity_type"],
                name="institution_partner_241130_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnershipactivity",
            index=models.Index(
                fields=["activity_date"], name="institution_activit_3be15e_idx"
            ),
        ),
    ]
