# Generated by Django 5.2 on 2025-07-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_universityregistrationcode_codeusagelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeusagelog',
            name='registration_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='institutions.universityregistrationcode'),
        ),
    ]
