# Generated by Django 5.1.7 on 2025-08-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_course_department_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
