# Generated by Django 5.1.7 on 2025-07-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change'), ('config_change', 'Configuration Change'), ('user_registration', 'User Registration'), ('password_reset_request', 'Password Reset Request'), ('password_reset_confirm', 'Password Reset Confirmation'), ('password_change', 'Password Change'), ('email_verification', 'Email Verification'), ('email_verification_success', 'Email Verification Success'), ('invite_created', 'Invite Created'), ('invite_used', 'Invite Used'), ('invite_registration', 'Invite Registration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('password_reset_request', 'Password Reset Request'), ('password_reset_confirm', 'Password Reset Confirmation'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity'), ('data_access', 'Data Access'), ('permission_denied', 'Permission Denied'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('csrf_attack', 'CSRF Attack Attempt'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attack Attempt'), ('user_registration', 'User Registration'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('brute_force_attempt', 'Brute Force Attempt'), ('user_profile_change', 'User Profile Change'), ('email_verification_success', 'Email Verification Success'), ('email_verification_failed', 'Email Verification Failed'), ('failed_password_change', 'Failed Password Change'), ('invite_created', 'Invite Created'), ('invite_used', 'Invite Used'), ('invite_registration', 'Invite Registration'), ('2fa_login_failed', '2FA Login Failed'), ('2fa_otp_generated', '2FA OTP Generated'), ('2fa_verify_failed', '2FA Verification Failed'), ('2fa_verify_success', '2FA Verification Success'), ('profile_created', 'Profile Created'), ('config_change', 'Configuration Change'), ('ip_blocked', 'IP Address Blocked')], max_length=50),
        ),
    ]
