# Generated by Django 5.2 on 2025-08-01 08:57

import security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, validators=[security.models.validate_ip_address]),
        ),
    ]
