# Generated by Django 5.1.7 on 2025-06-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_loginhistory_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
