# Generated by Django 5.2.6 on 2026-01-15 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("institution_id", models.UUIDField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
