# Generated by Django 5.2.6 on 2026-01-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="institution_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
