# Generated by Django 5.2.6 on 2026-01-15 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_institution_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInstitutionAffiliation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField()),
                ("institution_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "claimed_via",
                    models.CharField(
                        choices=[("domain", "Domain"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "student_institution_affiliations",
                "unique_together": {("student_id", "institution_id")},
            },
        ),
    ]
