# Generated by Django 5.2.6 on 2026-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_studentinstitutionaffiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admission_letter",
            field=models.FileField(blank=True, upload_to="students/admission_letters/"),
        ),
        migrations.AddField(
            model_name="student",
            name="course_of_study",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="current_year",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="cv",
            field=models.FileField(blank=True, upload_to="students/cvs/"),
        ),
        migrations.AddField(
            model_name="student",
            name="id_document",
            field=models.FileField(blank=True, upload_to="students/id_documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
