# Generated by Django 5.2.6 on 2026-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_student_admission_letter_student_course_of_study_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinstitutionaffiliation",
            name="cohort_id",
            field=models.UUIDField(
                blank=True, help_text="Reference to Institution Cohort", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentinstitutionaffiliation",
            name="department_id",
            field=models.UUIDField(
                blank=True, help_text="Reference to Institution Department", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentinstitutionaffiliation",
            name="raw_cohort_input",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="studentinstitutionaffiliation",
            name="raw_department_input",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
