# Generated by Django 5.2.6 on 2026-01-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_studentinstitutionaffiliation_cohort_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="students/profile_pictures/"
            ),
        ),
    ]
