# Generated by Django 5.2.6 on 2026-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_student_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="trust_level",
            field=models.IntegerField(
                choices=[
                    (0, "Self-Registered"),
                    (1, "Document Verified"),
                    (2, "Institution Verified"),
                    (3, "Internship Completed"),
                    (4, "Completion Certified"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="trust_points",
            field=models.IntegerField(default=0),
        ),
    ]
