# Generated by Django 5.0.4 on 2026-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_trust_level_student_trust_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_letter_verified',
            field=models.BooleanField(default=False, help_text='Admission letter verified'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_letter_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cv_verified',
            field=models.BooleanField(default=False, help_text='CV verified by institution admin'),
        ),
        migrations.AddField(
            model_name='student',
            name='cv_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_document_verified',
            field=models.BooleanField(default=False, help_text='ID document verified'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_document_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
