# Generated by Django 5.0.4 on 2026-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_admission_letter_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinstitutionaffiliation',
            name='verification_document_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When student uploaded verification document', null=True),
        ),
        migrations.AddField(
            model_name='studentinstitutionaffiliation',
            name='verification_document_url',
            field=models.CharField(blank=True, help_text='URL to uploaded verification document', max_length=500, null=True),
        ),
    ]
