# Generated by Django 5.0.4 on 2026-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_add_affiliation_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='trust_level',
            field=models.IntegerField(choices=[(0, 'Self-Registered'), (1, 'Documents Uploaded'), (2, 'Institution Verified'), (3, 'Internship Completed'), (4, 'Completion Certified')], default=0),
        ),
    ]
