# Generated by Django 5.2.3 on 2025-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_institution_user_national_id_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
