# Generated by Django 5.2.1 on 2025-07-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250702_1141'),
    ]

    operations = [
    ]
