# Generated by Django 5.1.7 on 2025-07-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email_verified_alter_user_institution'),
        ('authentication', '0002_user_is_email_verified'),
    ]

    operations = [
    ]
