# Generated by Django 5.1.7 on 2025-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20250708_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
