# Generated by Django 4.2.7 on 2025-09-03 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "require_cover_letter",
                    models.BooleanField(
                        default=False,
                        help_text="Require applicants to submit a cover letter",
                    ),
                ),
                (
                    "enable_custom_questions",
                    models.BooleanField(
                        default=False, help_text="Enable custom application questions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Requirement",
                "verbose_name_plural": "Application Requirements",
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (JPG, PNG, or SVG format)",
                        null=True,
                        upload_to="company_logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg"]
                            )
                        ],
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for the logo",
                        max_length=255,
                    ),
                ),
                (
                    "default_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Visible to all users"),
                            (
                                "restricted",
                                "Restricted - Visible to selected institutions",
                            ),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "default_require_cover_letter",
                    models.BooleanField(
                        default=False,
                        help_text="Require cover letter by default for new opportunities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="CustomApplicationQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_text",
                    models.TextField(help_text="The question to ask applicants"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text Answer"),
                            ("textarea", "Long Text Answer"),
                            ("multiple", "Multiple Choice"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Whether this question is required"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which questions appear"
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of choices for multiple choice questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Application Question",
                "verbose_name_plural": "Custom Application Questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Opportunity image (JPG or PNG format)",
                        upload_to="opportunity_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for the image",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Image",
                "verbose_name_plural": "Opportunity Images",
            },
        ),
        migrations.CreateModel(
            name="VisibilityControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility_type",
                    models.CharField(
                        choices=[
                            ("public", "Public - Visible to all users"),
                            (
                                "restricted",
                                "Restricted - Visible to selected institutions",
                            ),
                        ],
                        db_index=True,
                        default="public",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visibility Control",
                "verbose_name_plural": "Visibility Controls",
            },
        ),
    ]
