# Generated by Django 5.2.4 on 2025-07-25 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="profile_pics/default.jpg",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                ("phone_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=255)),
                ("company_description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1000+", "1000+ employees"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employer",
                "verbose_name_plural": "Employers",
                "db_table": "employers_employer",
            },
        ),
    ]
