# Generated by Django 4.2.7 on 2025-09-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        ("internship", "0001_initial"),
        ("users", "0001_initial"),
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visibilitycontrol",
            name="internship",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_control",
                to="internship.internship",
            ),
        ),
        migrations.AddField(
            model_name="visibilitycontrol",
            name="restricted_institutions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Institutions that can view this opportunity (only for restricted visibility)",
                related_name="restricted_opportunities",
                to="institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="opportunityimage",
            name="internship",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_image",
                to="internship.internship",
            ),
        ),
        migrations.AddField(
            model_name="customapplicationquestion",
            name="application_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_questions",
                to="employers.applicationrequirement",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="employer_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_settings",
                to="users.employerprofile",
            ),
        ),
        migrations.AddField(
            model_name="applicationrequirement",
            name="internship",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_requirement",
                to="internship.internship",
            ),
        ),
    ]
