# Generated by Django 5.2.6 on 2026-01-18 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0008_institutionrequest_institution_trackin_0176fe_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSTITUTION_VERIFIED", "Institution Verified"),
                            ("INSTITUTION_REJECTED", "Institution Rejected"),
                            ("USER_SUSPENDED", "User Suspended"),
                            ("USER_REACTIVATED", "User Reactivated"),
                            ("USER_ROLE_CHANGED", "User Role Changed"),
                            ("STAFF_CREATED", "Staff Member Created"),
                            ("STAFF_REVOKED", "Staff Member Revoked"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Additional details about the action"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string for forensic analysis"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institutions.institution",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_by_admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Action Log",
                "verbose_name_plural": "Admin Action Logs",
                "db_table": "admin_action_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"],
                        name="admin_actio_actor_i_1ef5f0_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="admin_actio_action_bb497a_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="admin_actio_target__b60369_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformStaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin (Root Authority)"),
                            ("PLATFORM_ADMIN", "Platform Admin (Operations)"),
                            ("MODERATOR", "Platform Moderator / Support"),
                            ("AUDITOR", "System Auditor"),
                        ],
                        help_text="Platform staff role - authority is explicit and revocable",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this staff member's authority was revoked",
                        null=True,
                    ),
                ),
                (
                    "invite_token",
                    models.CharField(
                        blank=True,
                        help_text="One-time token for invite-based onboarding",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "invite_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the invite token expires", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this staff member currently has platform authority",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created this staff member (None for genesis creation)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_platform_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Staff Profile",
                "verbose_name_plural": "Platform Staff Profiles",
                "db_table": "admin_platform_staff_profile",
                "indexes": [
                    models.Index(
                        fields=["role", "is_active"], name="admin_platf_role_ad82fe_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="admin_platf_created_696479_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin (Root Authority)"),
                            ("PLATFORM_ADMIN", "Platform Admin (Operations)"),
                            ("MODERATOR", "Platform Moderator / Support"),
                            ("AUDITOR", "System Auditor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional note about the invite"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_staff_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_staff_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Invite",
                "verbose_name_plural": "Staff Invites",
                "db_table": "admin_staff_invite",
                "indexes": [
                    models.Index(fields=["token"], name="admin_staff_token_741bab_idx"),
                    models.Index(
                        fields=["email", "expires_at"],
                        name="admin_staff_email_6ee049_idx",
                    ),
                ],
            },
        ),
    ]
