# Generated by Django 5.2.6 on 2026-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("INSTITUTION_VERIFIED", "Institution Verified"),
                    ("INSTITUTION_REJECTED", "Institution Rejected"),
                    ("USER_SUSPENDED", "User Suspended"),
                    ("USER_REACTIVATED", "User Reactivated"),
                    ("USER_ROLE_CHANGED", "User Role Changed"),
                    ("STAFF_CREATED", "Staff Member Created"),
                    ("STAFF_REVOKED", "Staff Member Revoked"),
                    ("OUTREACH_SENT", "Outreach Email Sent"),
                ],
                max_length=30,
            ),
        ),
    ]
