# Generated by Django 5.2.6 on 2026-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_admin", "0002_alter_adminactionlog_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminactionlog",
            name="target_institution",
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="target_institution_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
