# Generated by Django 5.2.4 on 2025-07-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
        ("users", "0005_remove_studentprofile_profile_completion"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_date", models.DateField()),
                ("activity_type", models.CharField(max_length=32)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date"],
                "unique_together": {("student", "activity_date", "activity_type")},
            },
        ),
    ]
