# Generated by Django 4.2.23 on 2025-08-27 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Skill Tag",
                "verbose_name_plural": "Skill Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("business", "Business"),
                            ("marketing", "Marketing"),
                            ("design", "Design"),
                            ("finance", "Finance"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("engineering", "Engineering"),
                            ("research", "Research"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("on-site", "On-site"),
                            ("hybrid", "Hybrid"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, State/Province, Country",
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        help_text="Duration in weeks (1-52)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "stipend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly stipend amount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        blank=True, default=list, help_text="List of required skills"
                    ),
                ),
                (
                    "preferred_skills",
                    models.JSONField(
                        blank=True, default=list, help_text="List of preferred skills"
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(
                        blank=True, help_text="General eligibility requirements"
                    ),
                ),
                (
                    "min_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum GPA requirement (0.0-4.0 scale)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(4.0),
                        ],
                    ),
                ),
                (
                    "required_year_of_study",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of acceptable years of study (e.g., [2, 3, 4])",
                    ),
                ),
                (
                    "required_majors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of acceptable majors/courses",
                    ),
                ),
                ("deadline", models.DateTimeField(db_index=True)),
                (
                    "max_applications",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of applications allowed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("institution-only", "Institution Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "employer_id",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Reference to employer in user service"
                    ),
                ),
                (
                    "institution_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reference to institution in user service",
                        null=True,
                    ),
                ),
                (
                    "verified_by_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reference to institution profile that verified this",
                        null=True,
                    ),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "partner_institution_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Institution this internship is specifically for",
                        null=True,
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of benefits (e.g., ['Health Insurance', 'Flexible Hours'])",
                    ),
                ),
                (
                    "application_instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for applicants"
                    ),
                ),
                (
                    "skill_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="internships",
                        to="internships.skilltag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internship",
                "verbose_name_plural": "Internships",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "location_type"],
                        name="internships_categor_835272_idx",
                    ),
                    models.Index(
                        fields=["deadline", "is_active"],
                        name="internships_deadlin_c3cc0d_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="internships_start_d_e8f995_idx",
                    ),
                    models.Index(
                        fields=["employer_id", "is_active"],
                        name="internships_employe_53bbad_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "created_at"],
                        name="internships_is_feat_521057_idx",
                    ),
                ],
            },
        ),
    ]
