# Generated by Django 5.2.6 on 2026-01-24 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "institution_id",
                    models.UUIDField(
                        help_text="The institution owning this internship process"
                    ),
                ),
                (
                    "employer_id",
                    models.UUIDField(help_text="The employer providing the internship"),
                ),
                (
                    "student_id",
                    models.UUIDField(
                        blank=True, help_text="The student (if assigned)", null=True
                    ),
                ),
                (
                    "opportunity_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Link to the parent opportunity if applicable",
                        null=True,
                    ),
                ),
                ("institution_supervisor_id", models.UUIDField(blank=True, null=True)),
                ("employer_supervisor_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("APPLIED", "Applied"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("ACCEPTED", "Accepted"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                            ("CERTIFIED", "Certified"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "internships",
                "indexes": [
                    models.Index(
                        fields=["status"], name="internships_status_c67f10_idx"
                    ),
                    models.Index(
                        fields=["student_id"], name="internships_student_1b4ac7_idx"
                    ),
                    models.Index(
                        fields=["institution_id"], name="internships_institu_3fccef_idx"
                    ),
                    models.Index(
                        fields=["employer_id"], name="internships_employe_46d6cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InternshipEvidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_by", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("REVIEWED", "Reviewed"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="internships.internship",
                    ),
                ),
            ],
            options={
                "db_table": "internship_evidence",
            },
        ),
    ]
