# Generated by Django 5.2.6 on 2026-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="employer_id",
            field=models.UUIDField(
                blank=True, help_text="The employer providing the internship", null=True
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="institution_id",
            field=models.UUIDField(
                blank=True,
                help_text="The institution owning this internship process",
                null=True,
            ),
        ),
    ]
