# Generated by Django 5.2.6 on 2026-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0002_alter_internship_employer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of positions available"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="internship",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="internship",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ONSITE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("APPLIED", "Applied"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("TERMINATED", "Terminated"),
                    ("CERTIFIED", "Certified"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
