# Generated by Django 5.2.6 on 2026-01-24 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0003_internship_capacity_internship_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipevidence",
            name="evidence_type",
            field=models.CharField(
                choices=[
                    ("LOGBOOK", "Logbook Entry"),
                    ("MILESTONE", "Milestone Completion"),
                    ("REPORT", "Report"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reported_by", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.UUIDField(blank=True, null=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="internships.internship",
                    ),
                ),
            ],
            options={
                "db_table": "internship_incidents",
            },
        ),
    ]
