# Generated by Django 5.2.6 on 2026-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0004_internshipevidence_evidence_type_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="cohort",
            field=models.CharField(
                blank=True,
                help_text="Cohort associated with this internship (e.g., Class of 2025)",
                max_length=255,
            ),
        ),
    ]
