# Generated by Django 5.2.6 on 2026-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0005_internship_cohort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internshipevidence",
            name="file_url",
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="file",
            field=models.FileField(blank=True, upload_to="internships/evidence/"),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="internshipevidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
