# Generated by Django 5.2.6 on 2026-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0006_remove_internshipevidence_file_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="application_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of student profile at time of application",
            ),
        ),
    ]
