# Generated by Django 5.2.6 on 2026-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0007_internship_application_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
