# Generated by Django 5.2.6 on 2026-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0008_internship_application_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="Duration description (e.g. '3 months')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="is_institution_restricted",
            field=models.BooleanField(
                default=False,
                help_text="If true, only students from the owning institution can apply",
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="application_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
