# Generated by Django 5.2.6 on 2026-01-27 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0009_internship_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_testimonial",
                    models.TextField(help_text="Quote from the student"),
                ),
                (
                    "employer_feedback",
                    models.TextField(
                        blank=True, help_text="Feedback from the employer"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "internship",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_story",
                        to="internships.internship",
                    ),
                ),
            ],
            options={
                "db_table": "internship_success_stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
