# Generated by Django 5.2.6 on 2026-01-30 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0010_successstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField(help_text="The student applying")),
                ("institution_supervisor_id", models.UUIDField(blank=True, null=True)),
                ("employer_supervisor_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                            ("CERTIFIED", "Certified"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                (
                    "application_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of student profile at time of application",
                    ),
                ),
            ],
            options={
                "db_table": "internship_applications",
            },
        ),
        migrations.RemoveField(
            model_name="successstory",
            name="internship",
        ),
        migrations.RemoveField(
            model_name="internshipevidence",
            name="internship",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="internship",
        ),
        migrations.AddField(
            model_name="incident",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="internships.internshipapplication",
            ),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="internships.internshipapplication",
            ),
        ),
        migrations.AddField(
            model_name="successstory",
            name="application",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="success_story",
                to="internships.internshipapplication",
            ),
        ),
        migrations.CreateModel(
            name="InternshipOpportunity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("department", models.CharField(blank=True, max_length=255)),
                (
                    "cohort",
                    models.CharField(
                        blank=True,
                        help_text="Cohort associated with this internship (e.g., Class of 2025)",
                        max_length=255,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of positions available"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("ONSITE", "On-site"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="ONSITE",
                        max_length=20,
                    ),
                ),
                (
                    "institution_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The institution owning this internship process",
                        null=True,
                    ),
                ),
                (
                    "employer_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The employer providing the internship",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Duration description (e.g. '3 months')",
                        max_length=50,
                    ),
                ),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "is_institution_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only students from the owning institution can apply",
                    ),
                ),
            ],
            options={
                "db_table": "internship_opportunities",
                "indexes": [
                    models.Index(
                        fields=["status"], name="internship__status_c02889_idx"
                    ),
                    models.Index(
                        fields=["institution_id"], name="internship__institu_b9f324_idx"
                    ),
                    models.Index(
                        fields=["employer_id"], name="internship__employe_09cf39_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="internships.internshipopportunity",
            ),
        ),
        migrations.DeleteModel(
            name="Internship",
        ),
        migrations.AddIndex(
            model_name="internshipapplication",
            index=models.Index(fields=["status"], name="internship__status_f17797_idx"),
        ),
        migrations.AddIndex(
            model_name="internshipapplication",
            index=models.Index(
                fields=["student_id"], name="internship__student_dfca0f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="internshipapplication",
            unique_together={("opportunity", "student_id")},
        ),
    ]
