# Generated by Django 5.2.6 on 2026-01-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "internships",
            "0011_internshipapplication_remove_successstory_internship_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="cover_letter",
            field=models.TextField(
                blank=True, help_text="Why the student is a good fit"
            ),
        ),
    ]
