# Generated by Django 5.2.6 on 2026-01-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0012_internshipapplication_cover_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipevidence",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Private comments visible only to the supervisor"
            ),
        ),
        migrations.AlterField(
            model_name="internshipevidence",
            name="review_notes",
            field=models.TextField(
                blank=True, help_text="Public comments visible to the student"
            ),
        ),
        migrations.AlterField(
            model_name="internshipevidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("REVISION_REQUIRED", "Revision Required"),
                ],
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
