# Generated by Django 5.2.6 on 2026-01-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0013_internshipevidence_private_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipevidence",
            name="employer_review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="employer_review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("REVISION_REQUIRED", "Revision Required"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="employer_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="employer_reviewed_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="institution_review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="institution_review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("REVIEWED", "Reviewed"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("REVISION_REQUIRED", "Revision Required"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="institution_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="institution_reviewed_by",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
