# Generated by Django 5.2.6 on 2026-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internships", "0014_internshipevidence_employer_review_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="internshipevidence",
            old_name="private_notes",
            new_name="employer_private_notes",
        ),
        migrations.RemoveField(
            model_name="internshipevidence",
            name="review_notes",
        ),
        migrations.RemoveField(
            model_name="internshipevidence",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="internshipevidence",
            name="reviewed_by",
        ),
        migrations.AddField(
            model_name="internshipevidence",
            name="institution_private_notes",
            field=models.TextField(
                blank=True, help_text="Private comments visible only to the supervisor"
            ),
        ),
        migrations.AlterField(
            model_name="internshipevidence",
            name="employer_review_notes",
            field=models.TextField(
                blank=True, help_text="Public comments visible to the student"
            ),
        ),
        migrations.AlterField(
            model_name="internshipevidence",
            name="institution_review_notes",
            field=models.TextField(
                blank=True, help_text="Public comments visible to the student"
            ),
        ),
    ]
