# Generated by Django 5.2.6 on 2026-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "internships",
            "0015_rename_private_notes_internshipevidence_employer_private_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="final_feedback",
            field=models.TextField(
                blank=True, help_text="Authoritative feedback from supervisor(s)"
            ),
        ),
        migrations.AddField(
            model_name="internshipapplication",
            name="final_rating",
            field=models.PositiveIntegerField(
                blank=True, help_text="Numeric rating (1-5)", null=True
            ),
        ),
    ]
