# Generated by Django 5.0.4 on 2026-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0020_incident_workflow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supervisorassignment',
            name='unique_supervisor_assignment',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='internship__incident_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='internshipopportunity',
            name='internship_op_status_appdeadline_idx',
        ),
        migrations.RemoveIndex(
            model_name='internshipopportunity',
            name='internship_op_appdeadline_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='internshipopportunity',
            name='internship_op_status_deadline_created_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisorassignment',
            new_name='internship__status_2ac552_idx',
            old_name='internship__status__idx',
        ),
        migrations.RenameIndex(
            model_name='supervisorassignment',
            new_name='internship__applica_8c9985_idx',
            old_name='internship__applicat_assignm__idx',
        ),
        migrations.RenameIndex(
            model_name='supervisorassignment',
            new_name='internship__supervi_ef9e3b_idx',
            old_name='internship__supervis__idx',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version for optimistic locking'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='withdrawal_reason',
            field=models.TextField(blank=True, help_text='Why student withdrew'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='When student withdrew', null=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('CERTIFIED', 'Certified'), ('WITHDRAWN', 'Withdrawn by Student')], default='APPLIED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='supervisorassignment',
            unique_together={('application', 'supervisor_id', 'assignment_type')},
        ),
    ]
