# Generated by Django 5.2.6 on 2026-01-15 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSuggestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("student_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "institution_suggestions",
            },
        ),
        migrations.AddField(
            model_name="institution",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("unverified", "Unverified"),
                    ("verified", "Verified"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="verification_method",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
