# Generated by Django 5.2.6 on 2026-01-16 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0002_institutionsuggestion_institution_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionInterest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField()),
                ("raw_name", models.CharField(max_length=255)),
                ("email_domain", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "institution_interests",
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="institution_student_3a0940_idx"
                    ),
                    models.Index(
                        fields=["email_domain"], name="institution_email_d_73b4da_idx"
                    ),
                ],
            },
        ),
    ]
