# Generated by Django 5.2.6 on 2026-01-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0003_institutioninterest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutioninterest",
            name="student_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
