# Generated by Django 5.2.6 on 2026-01-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0004_alter_institutioninterest_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutioninterest",
            name="user_email",
            field=models.EmailField(
                blank=True,
                help_text="User's email for communication when institution is onboarded",
                max_length=254,
            ),
        ),
    ]
