# Generated by Django 5.2.6 on 2026-01-17 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0005_institutioninterest_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution_name", models.CharField(max_length=255)),
                ("website_url", models.URLField(max_length=500)),
                (
                    "requested_domains",
                    models.JSONField(
                        default=list, help_text="Array of official email domains"
                    ),
                ),
                ("representative_name", models.CharField(max_length=255)),
                ("representative_email", models.EmailField(max_length=254)),
                ("representative_role", models.CharField(max_length=255)),
                ("representative_phone", models.CharField(blank=True, max_length=20)),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="institution_requests/"
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "institution_requests",
                "indexes": [
                    models.Index(
                        fields=["status"], name="institution_status_7cc6ac_idx"
                    ),
                    models.Index(
                        fields=["representative_email"],
                        name="institution_represe_3d73d6_idx",
                    ),
                    models.Index(
                        fields=["institution_name"],
                        name="institution_institu_067511_idx",
                    ),
                ],
            },
        ),
    ]
