# Generated by Django 5.2.6 on 2026-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0007_institutionrequest_tracking_code"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="institutionrequest",
            index=models.Index(
                fields=["tracking_code"], name="institution_trackin_0176fe_idx"
            ),
        ),
    ]
