# Generated by Django 5.2.6 on 2026-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0009_fix_institution_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionrequest",
            name="rejection_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid_domain", "Invalid or unverifiable email domain"),
                    (
                        "insufficient_documentation",
                        "Insufficient supporting documentation",
                    ),
                    (
                        "unverifiable_institution",
                        "Cannot verify institution legitimacy",
                    ),
                    (
                        "duplicate_request",
                        "Duplicate of existing request or institution",
                    ),
                    ("spam_suspicious", "Suspicious activity or spam indicators"),
                    ("other", "Other reason (see detailed explanation)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("unverified", "Unverified"),
                    ("verified", "Verified"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
    ]
