# Generated by Django 5.2.6 on 2026-01-22 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0010_institutionrequest_rejection_reason_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(default="INSTITUTION_ADMIN", max_length=50)),
                (
                    "token_hash",
                    models.CharField(
                        help_text="Hashed token for security", max_length=128
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "db_table": "institution_invites",
                "indexes": [
                    models.Index(
                        fields=["email", "status"], name="institution_email_ac2067_idx"
                    ),
                    models.Index(
                        fields=["token_hash"], name="institution_token_h_612d97_idx"
                    ),
                ],
            },
        ),
    ]
