# Generated by Django 5.2.6 on 2026-01-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0012_institutionstaff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("supervisor", "Supervisor"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
