# Generated by Django 5.2.6 on 2026-01-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0013_alter_institutionstaff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutioninvite",
            name="cohort",
            field=models.CharField(
                blank=True,
                help_text="Cohort assignment for supervisors",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="institutioninvite",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department assignment for supervisors",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="institutionstaff",
            name="cohort",
            field=models.CharField(
                blank=True,
                help_text="Cohort assignment for supervisors",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="institutionstaff",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department assignment for supervisors",
                max_length=255,
            ),
        ),
    ]
