# Generated by Django 5.2.6 on 2026-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0014_institutioninvite_cohort_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="institution",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="institution",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="website_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
