# Generated by Django 5.2.6 on 2026-01-25 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0015_institution_address_institution_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of alternative names for matching",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "db_table": "institution_departments",
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("intake_label", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="institutions.department",
                    ),
                ),
            ],
            options={
                "db_table": "institution_cohorts",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["institution", "is_active"],
                name="institution_institu_dcb560_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("institution", "name")},
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(
                fields=["department", "is_active"],
                name="institution_departm_de05a8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cohort",
            unique_together={("department", "name")},
        ),
    ]
