# Generated by Django 5.2.6 on 2026-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0016_department_cohort_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="trust_level",
            field=models.IntegerField(
                choices=[
                    (0, "Registered"),
                    (1, "Active"),
                    (2, "High Trust"),
                    (3, "Strategic Partner"),
                ],
                default=0,
            ),
        ),
    ]
