# Generated by Django 5.2.6 on 2026-01-27 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0017_institution_trust_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionStaffProfileRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_changes",
                    models.JSONField(
                        help_text="Dictionary of requested changes (first_name, last_name, email)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_feedback", models.TextField(blank=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile_requests",
                        to="institutions.institution",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staff_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_requests",
                        to="institutions.institutionstaff",
                    ),
                ),
            ],
            options={
                "db_table": "institution_staff_profile_requests",
                "indexes": [
                    models.Index(
                        fields=["institution", "status"],
                        name="institution_institu_5eb176_idx",
                    ),
                    models.Index(
                        fields=["staff", "status"],
                        name="institution_staff_i_e502fc_idx",
                    ),
                ],
            },
        ),
    ]
