# Generated by Django 5.2.6 on 2026-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0018_institutionstaffprofilerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="institution_logos/"
            ),
        ),
    ]
