# Generated by Django 5.2.6 on 2026-01-15 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.UUIDField()),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ledger_events",
                "ordering": ["occurred_at"],
            },
        ),
    ]
