# Generated by Django 5.2.6 on 2026-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerevent",
            name="actor_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="hash",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="ledgerevent",
            index=models.Index(
                fields=["event_type"], name="ledger_even_event_t_56b184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerevent",
            index=models.Index(
                fields=["entity_id"], name="ledger_even_entity__aafc1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerevent",
            index=models.Index(
                fields=["actor_id"], name="ledger_even_actor_i_566b2a_idx"
            ),
        ),
    ]
