# Generated by Django 5.2.6 on 2026-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_ledgerevent_actor_id_ledgerevent_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerevent",
            name="previous_hash",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
