# Generated by Django 5.2.6 on 2026-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_ledgerevent_previous_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerevent",
            name="actor_role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
