# Generated by Django 5.2.3 on 2025-07-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('internship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the notification.')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), (
                    'push', 'Push Notification')], help_text='Type of notification (email, SMS, push).', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the notification was created.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if the user has read the notification.')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')],
                 default='pending', help_text='Delivery status of the notification.', max_length=10)),
                ('related_application', models.ForeignKey(blank=True, help_text='Link to an application if the notification is status-related.',
                 null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='application.application')),
                ('related_internship', models.ForeignKey(blank=True, help_text='Link to an internship if the notification is relevant to an internship.',
                 null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='internship.internship')),
                ('user', models.ForeignKey(help_text='The recipient of the notification.',
                 on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
