# Generated by Django 5.2.6 on 2026-02-07 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_by_id", models.UUIDField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "contact_submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="contact_sub_email_903821_idx"),
                    models.Index(
                        fields=["is_processed"], name="contact_sub_is_proc_d98742_idx"
                    ),
                ],
            },
        ),
    ]
