version: '3.8'

services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: edulink_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - edulink_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache & Result Backend
  redis:
    image: redis:7-alpine
    container_name: edulink_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - edulink_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: edulink_postgres
    environment:
      POSTGRES_DB: edulink
      POSTGRES_USER: edulink_user
      POSTGRES_PASSWORD: edulink_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.psql:/docker-entrypoint-initdb.d/init-db.psql
    networks:
      - edulink_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edulink_user -d edulink"]
      interval: 30s
      timeout: 10s
      retries: 5

  # API Gateway
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: edulink_api_gateway
    ports:
      - "8000:8000"
    environment:
      - INTERNSHIP_SERVICE_URL=http://internship_service:8001
      - APPLICATION_SERVICE_URL=http://application_service:8002
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      internship_service:
        condition: service_healthy
      application_service:
        condition: service_healthy
    networks:
      - edulink_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Internship Service
  internship_service:
    build:
      context: ./internship_service
      dockerfile: Dockerfile
    container_name: edulink_internship_service
    ports:
      - "8001:8001"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://edulink_user:edulink_password@postgres:5432/edulink_internships
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edulink_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./shared:/app/shared

  # Application Service
  application_service:
    build:
      context: ./application_service
      dockerfile: Dockerfile
    container_name: edulink_application_service
    ports:
      - "8002:8002"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://edulink_user:edulink_password@postgres:5432/edulink_applications
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - INTERNSHIP_SERVICE_URL=http://internship_service:8001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edulink_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./shared:/app/shared

  # Celery Worker for Internship Service
  internship_worker:
    build:
      context: ./internship_service
      dockerfile: Dockerfile
    container_name: edulink_internship_worker
    command: celery -A internship_service worker -l info -Q internship_queue,shared_queue
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://edulink_user:edulink_password@postgres:5432/edulink_internships
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edulink_network
    volumes:
      - ./shared:/app/shared
    restart: unless-stopped

  # Celery Worker for Application Service
  application_worker:
    build:
      context: ./application_service
      dockerfile: Dockerfile
    container_name: edulink_application_worker
    command: celery -A application_service worker -l info -Q application_queue,notifications,shared_queue
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://edulink_user:edulink_password@postgres:5432/edulink_applications
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - INTERNSHIP_SERVICE_URL=http://internship_service:8001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edulink_network
    volumes:
      - ./shared:/app/shared
    restart: unless-stopped

  # Celery Beat Scheduler
  celery_beat:
    build:
      context: ./internship_service
      dockerfile: Dockerfile
    container_name: edulink_celery_beat
    command: celery -A internship_service beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://edulink_user:edulink_password@postgres:5432/edulink_internships
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edulink_network
    volumes:
      - ./shared:/app/shared
    restart: unless-stopped

  # Flower - Celery Monitoring
  flower:
    build:
      context: ./internship_service
      dockerfile: Dockerfile
    container_name: edulink_flower
    command: celery -A internship_service flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://edulink_user:edulink_password@postgres:5432/edulink_internships
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - edulink_network
    volumes:
      - ./shared:/app/shared
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  edulink_network:
    driver: bridge