# Generated by Django 5.2.6 on 2026-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("welcome", "Welcome"),
                    ("password_changed", "Password Changed"),
                    (
                        "internship_application_submitted",
                        "Internship Application Submitted",
                    ),
                    (
                        "internship_application_reviewed",
                        "Internship Application Reviewed",
                    ),
                    ("internship_accepted", "Internship Accepted"),
                    ("internship_rejected", "Internship Rejected"),
                    ("logbook_submitted", "Logbook Submitted"),
                    ("logbook_reviewed", "Logbook Reviewed"),
                    ("trust_tier_changed", "Trust Tier Changed"),
                    ("document_uploaded", "Document Uploaded"),
                    ("document_verified", "Document Verified"),
                    ("institution_onboarded", "Institution Onboarded"),
                    ("employer_request_received", "Employer Request Received"),
                    ("employer_request_approved", "Employer Request Approved"),
                    ("employer_request_rejected", "Employer Request Rejected"),
                    ("employer_onboarded", "Employer Onboarded"),
                ],
                max_length=50,
            ),
        ),
    ]
