# Generated by Django 5.2.6 on 2026-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_alter_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationtoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user",
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="user_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user_id"], name="notificatio_user_id_65d268_idx"
            ),
        ),
    ]
