# Generated by Django 5.2.6 on 2026-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_remove_emailverificationtoken_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["idempotency_key"], name="notificatio_idempot_aa93f8_idx"
            ),
        ),
    ]
