name: edulink_ke

description: >
  EduLink KE - A platform for students, schools, and employers to manage internships, applications, and certifications.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.2.0
  image_picker: ^1.0.7
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.2

  # The following adds the Cupertino Icons font to your application.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    # Add asset folders here if needed
    # - assets/images/ 
    - assets/kuccps_institutions.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
